export const flags = [
    {raceName: "N/A"},
    {raceName: "70th Anniversary Grand Prix", flagImage: <img id="greatBritainFlag" src="https://flagsapi.com/GB/flat/32.png" alt="British flag"></img>},
    {raceName: "Abu Dhabi Grand Prix", flagImage: <img id="UAEFlag" src="https://flagsapi.com/AE/flat/32.png" alt="United Arab Emirates flag"></img>},
    {raceName: "Australian Grand Prix", flagImage: <img id="australianFlag" src="https://flagsapi.com/AU/flat/32.png" alt="Australian flag"></img>},
    {raceName: "Austrian Grand Prix", flagImage: <img id="austrianFlag" src="https://flagsapi.com/AT/flat/32.png" alt="Austrian flag"></img>},
    {raceName: "Azerbaijan Grand Prix", flagImage: <img id="azerbaijanFlag" src="https://flagsapi.com/AZ/flat/32.png" alt="Azerbaijan flag"></img>},
    {raceName: "Bahrain Grand Prix", flagImage: <img id="bahrainFlag" src="https://flagsapi.com/BH/flat/32.png" alt="Flag of Bahrain"></img>},
    {raceName: "Belgian Grand Prix", flagImage: <img id="belgianFlag" src="https://flagsapi.com/BE/flat/32.png" alt="Belgian flag"></img>},
    {raceName: "Brazilian Grand Prix", flagImage: <img id="brazilianFlag" src="https://flagsapi.com/BR/flat/32.png" alt="Brazilian flag"></img>},
    {raceName: "Canadian Grand Prix", flagImage: <img id="canadianFlag" src="https://flagsapi.com/CA/flat/32.png" alt="Canadian flag"></img>},
    {raceName: "Chinese Grand Prix", flagImage: <img id="chineseFlag" src="https://flagsapi.com/CN/flat/32.png" alt="Chinese flag"></img>},
    {raceName: "Emilia Romagna Grand Prix", flagImage: <img id="italianFlag" src="https://flagsapi.com/IT/flat/32.png" alt="Italian flag"></img>},
    {raceName: "Spanish Grand Prix", flagImage: <img id="spanishFlag" src="https://flagsapi.com/ES/flat/32.png" alt="Spanish flag"></img>},
    
    //flags api doesn't have EU flag, so will need to look elsewhere if EUR header is needed in future.
    //Azerbaijan flag used as placeholder as most recent European GP was in Azerbaijan (2016).
    {raceName: "European Grand Prix", flagImage: <img id="azerbaijanFlag" src="https://flagsapi.com/AZ/flat/32.png" alt="Azerbaijan flag"></img>},
    {raceName: "British Grand Prix", flagImage: <img id="greatBritainFlag" src="https://flagsapi.com/GB/flat/32.png" alt="British flag"></img>},
    {raceName: "Hungarian Grand Prix", flagImage: <img id="hungarianFlag" src="https://flagsapi.com/HU/flat/32.png" alt="Hungarian flag"></img>},
    {raceName: "Italian Grand Prix", flagImage: <img id="italianFlag" src="https://flagsapi.com/IT/flat/32.png" alt="Italian flag"></img>},
    {raceName: "Japanese Grand Prix", flagImage: <img id="japaneseFlag" src="https://flagsapi.com/JP/flat/32.png" alt="Japanese flag"></img>},
    {raceName: "Las Vegas Grand Prix", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
    {raceName: "Mexican Grand Prix", flagImage: <img id="mexicanFlag" src="https://flagsapi.com/MX/flat/32.png" alt="Mexican flag"></img>},
    {raceName: "Mexico City Grand Prix", flagImage: <img id="mexicanFlag" src="https://flagsapi.com/MX/flat/32.png" alt="Mexican flag"></img>},
    {raceName: "Miami Grand Prix", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
    {raceName: "Monaco Grand Prix", flagImage: <img id="monacoFlag" src="https://flagsapi.com/MC/flat/32.png" alt="Flag of Monaco"></img>},
    {raceName: "Dutch Grand Prix", flagImage: <img id="dutchFlag" src="https://flagsapi.com/NL/flat/32.png" alt="Dutch flag"></img>},
    {raceName: "Qatar Grand Prix", flagImage: <img id="qatarFlag" src="https://flagsapi.com/QA/flat/32.png" alt="Flag of Qatar"></img>},
    {raceName: "Saudi Arabian Grand Prix", flagImage: <img id="saudiArabianFlag" src="https://flagsapi.com/SA/flat/32.png" alt="Saudi Arabian flag"></img>},
    {raceName: "Singapore Grand Prix", flagImage: <img id="singaporeFlag" src="https://flagsapi.com/SG/flat/32.png" alt="Flag of Singapore"></img>},
    {raceName: "Sakhir Grand Prix", flagImage: <img id="bahrainFlag" src="https://flagsapi.com/BH/flat/32.png" alt="Flag of Bahrain"></img>},
    {raceName: "San Marino Grand Prix", flagImage: <img id="sanMarinoFlag" src="https://flagsapi.com/SM/flat/32.png" alt="Flag of San Marino"></img>},
    {raceName: "São Paulo Grand Prix", flagImage: <img id="brazilianFlag" src="https://flagsapi.com/BR/flat/32.png" alt="Brazilian flag"></img>},
    {raceName: "Styrian Grand Prix", flagImage: <img id="austrianFlag" src="https://flagsapi.com/AT/flat/32.png" alt="Austrian flag"></img>},
    {raceName: "United States Grand Prix", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
  ];