export const flags = [
    {raceName: "N/A"},
    {circuitId: 'silverstone', raceName: "70th Anniversary Grand Prix", url: "https://flagsapi.com/GB/flat/32.png", flagImage: <img id="greatBritainFlag" src="https://flagsapi.com/GB/flat/32.png" alt="British flag"></img>},
    {circuitId: 'yas_marina', raceName: "Abu Dhabi Grand Prix", url: "https://flagsapi.com/AE/flat/32.png", flagImage: <img id="UAEFlag" src="https://flagsapi.com/AE/flat/32.png" alt="United Arab Emirates flag"></img>},
    {circuitId: 'albert_park', raceName: "Australian Grand Prix", url: "https://flagsapi.com/AU/flat/32.png", flagImage: <img id="australianFlag" src="https://flagsapi.com/AU/flat/32.png" alt="Australian flag"></img>},
    {circuitId: 'red_bull_ring', raceName: "Austrian Grand Prix", url: "https://flagsapi.com/AT/flat/32.png", flagImage: <img id="austrianFlag" src="https://flagsapi.com/AT/flat/32.png" alt="Austrian flag"></img>},
    {circuitId: 'baku', raceName: "Azerbaijan Grand Prix", url: "https://flagsapi.com/AZ/flat/32.png", flagImage: <img id="azerbaijanFlag" src="https://flagsapi.com/AZ/flat/32.png" alt="Azerbaijan flag"></img>},
    {circuitId: 'bahrain', raceName: "Bahrain Grand Prix", url: "https://flagsapi.com/BH/flat/32.png", flagImage: <img id="bahrainFlag" src="https://flagsapi.com/BH/flat/32.png" alt="Flag of Bahrain"></img>},
    {circuitId: 'spa', raceName: "Belgian Grand Prix", url: "https://flagsapi.com/BE/flat/32.png", flagImage: <img id="belgianFlag" src="https://flagsapi.com/BE/flat/32.png" alt="Belgian flag"></img>},
    {circuitId: 'interlagos', raceName: "Brazilian Grand Prix", url: "https://flagsapi.com/BR/flat/32.png", flagImage: <img id="brazilianFlag" src="https://flagsapi.com/BR/flat/32.png" alt="Brazilian flag"></img>},
    {circuitId: 'villeneuve', raceName: "Canadian Grand Prix", url: "https://flagsapi.com/CA/flat/32.png", flagImage: <img id="canadianFlag" src="https://flagsapi.com/CA/flat/32.png" alt="Canadian flag"></img>},
    {circuitId: 'shanghai', raceName: "Chinese Grand Prix", url: "https://flagsapi.com/CN/flat/32.png", flagImage: <img id="chineseFlag" src="https://flagsapi.com/CN/flat/32.png" alt="Chinese flag"></img>},
    {circuitId: 'imola', raceName: "Emilia Romagna Grand Prix", url: "https://flagsapi.com/IT/flat/32.png", flagImage: <img id="italianFlag" src="https://flagsapi.com/IT/flat/32.png" alt="Italian flag"></img>},
    {circuitId: 'catalunya', raceName: "Spanish Grand Prix", url: "https://flagsapi.com/ES/flat/32.png", flagImage: <img id="spanishFlag" src="https://flagsapi.com/ES/flat/32.png" alt="Spanish flag"></img>},
    
    //flags api doesn't have EU flag, so will need to look elsewhere if EUR header is needed in future.
    //Azerbaijan flag used as placeholder as most recent European GP was in Azerbaijan (2016).
    {circuitId: 'baku', raceName: "European Grand Prix", url: "https://flagsapi.com/AZ/flat/32.png", flagImage: <img id="azerbaijanFlag" src="https://flagsapi.com/AZ/flat/32.png" alt="Azerbaijan flag"></img>},
    {circuitId: 'silverstone', raceName: "British Grand Prix", url: "https://flagsapi.com/GB/flat/32.png", flagImage: <img id="greatBritainFlag" src="https://flagsapi.com/GB/flat/32.png" alt="British flag"></img>},
    {circuitId: 'hungaroring', raceName: "Hungarian Grand Prix", url: "https://flagsapi.com/HU/flat/32.png", flagImage: <img id="hungarianFlag" src="https://flagsapi.com/HU/flat/32.png" alt="Hungarian flag"></img>},
    {circuitId: 'monza', raceName: "Italian Grand Prix", url: "https://flagsapi.com/IT/flat/32.png", flagImage: <img id="italianFlag" src="https://flagsapi.com/IT/flat/32.png" alt="Italian flag"></img>},
    {circuitId: 'suzuka', raceName: "Japanese Grand Prix", url: "https://flagsapi.com/JP/flat/32.png", flagImage: <img id="japaneseFlag" src="https://flagsapi.com/JP/flat/32.png" alt="Japanese flag"></img>},
    {circuitId: 'vegas', raceName: "Las Vegas Grand Prix", url: "https://flagsapi.com/US/flat/32.png", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
    {circuitId: 'rodriguez', raceName: "Mexican Grand Prix", url: "https://flagsapi.com/MX/flat/32.png", flagImage: <img id="mexicanFlag" src="https://flagsapi.com/MX/flat/32.png" alt="Mexican flag"></img>},
    {circuitId: 'rodriguez', raceName: "Mexico City Grand Prix", url: "https://flagsapi.com/MX/flat/32.png", flagImage: <img id="mexicanFlag" src="https://flagsapi.com/MX/flat/32.png" alt="Mexican flag"></img>},
    {circuitId: 'miami', raceName: "Miami Grand Prix", url: "https://flagsapi.com/US/flat/32.png", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
    {circuitId: 'monaco', raceName: "Monaco Grand Prix", url: "https://flagsapi.com/MC/flat/32.png", flagImage: <img id="monacoFlag" src="https://flagsapi.com/MC/flat/32.png" alt="Flag of Monaco"></img>},
    {circuitId: 'zandvoort', raceName: "Dutch Grand Prix", url: "https://flagsapi.com/NL/flat/32.png", flagImage: <img id="dutchFlag" src="https://flagsapi.com/NL/flat/32.png" alt="Dutch flag"></img>},
    {circuitId: 'losail', raceName: "Qatar Grand Prix", url: "https://flagsapi.com/QA/flat/32.png", flagImage: <img id="qatarFlag" src="https://flagsapi.com/QA/flat/32.png" alt="Flag of Qatar"></img>},
    {circuitId: 'jeddah', raceName: "Saudi Arabian Grand Prix", url: "https://flagsapi.com/SA/flat/32.png", flagImage: <img id="saudiArabianFlag" src="https://flagsapi.com/SA/flat/32.png" alt="Saudi Arabian flag"></img>},
    {circuitId: 'marina_bay', raceName: "Singapore Grand Prix", url: "https://flagsapi.com/SG/flat/32.png", flagImage: <img id="singaporeFlag" src="https://flagsapi.com/SG/flat/32.png" alt="Flag of Singapore"></img>},
    {circuitId: 'bahrain', raceName: "Sakhir Grand Prix", url: "https://flagsapi.com/BH/flat/32.png", flagImage: <img id="bahrainFlag" src="https://flagsapi.com/BH/flat/32.png" alt="Flag of Bahrain"></img>},
    {circuitId: 'imola', raceName: "San Marino Grand Prix", url: "https://flagsapi.com/SM/flat/32.png", flagImage: <img id="sanMarinoFlag" src="https://flagsapi.com/SM/flat/32.png" alt="Flag of San Marino"></img>},
    {circuitId: 'interlagos', raceName: "São Paulo Grand Prix", url: "https://flagsapi.com/BR/flat/32.png", flagImage: <img id="brazilianFlag" src="https://flagsapi.com/BR/flat/32.png" alt="Brazilian flag"></img>},
    {circuitId: 'red_bull_ring', raceName: "Styrian Grand Prix", url: "https://flagsapi.com/AT/flat/32.png",  flagImage: <img id="austrianFlag" src="https://flagsapi.com/AT/flat/32.png" alt="Austrian flag"></img>},
    {circuitId: 'americas', raceName: "United States Grand Prix", url: "https://flagsapi.com/US/flat/32.png", flagImage: <img id="USAFlag" src="https://flagsapi.com/US/flat/32.png" alt="American flag"></img>},
  ];